export const x = [
      {
        id: "tt0111161",
        rank: "1",
        title: "The Shawshank Redemption",
        fullTitle: "The Shawshank Redemption (1994)",
        year: "1994",
        image: "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Frank Darabont (dir.), Tim Robbins, Morgan Freeman",
        imDbRating: "9.2",
        imDbRatingCount: "2596857"
      },
      {
        id: "tt0068646",
        rank: "2",
        title: "The Godfather",
        fullTitle: "The Godfather (1972)",
        year: "1972",
        image: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,1,128,176_AL_.jpg",
        crew: "Francis Ford Coppola (dir.), Marlon Brando, Al Pacino",
        imDbRating: "9.2",
        imDbRatingCount: "1792213"
      },
      {
        id: "tt0468569",
        rank: "3",
        title: "The Dark Knight",
        fullTitle: "The Dark Knight (2008)",
        year: "2008",
        image: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Christopher Nolan (dir.), Christian Bale, Heath Ledger",
        imDbRating: "9.0",
        imDbRatingCount: "2568018"
      },
      {
        id: "tt0071562",
        rank: "4",
        title: "The Godfather Part II",
        fullTitle: "The Godfather Part II (1974)",
        year: "1974",
        image: "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,1,128,176_AL_.jpg",
        crew: "Francis Ford Coppola (dir.), Al Pacino, Robert De Niro",
        imDbRating: "9.0",
        imDbRatingCount: "1235752"
      },
      {
        id: "tt0050083",
        rank: "5",
        title: "12 Angry Men",
        fullTitle: "12 Angry Men (1957)",
        year: "1957",
        image: "https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb",
        imDbRating: "8.9",
        imDbRatingCount: "767224"
      },
      {
        id: "tt0108052",
        rank: "6",
        title: "Schindler's List",
        fullTitle: "Schindler's List (1993)",
        year: "1993",
        image: "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Steven Spielberg (dir.), Liam Neeson, Ralph Fiennes",
        imDbRating: "8.9",
        imDbRatingCount: "1321023"
      },
      {
        id: "tt0167260",
        rank: "7",
        title: "The Lord of the Rings: The Return of the King",
        fullTitle: "The Lord of the Rings: The Return of the King (2003)",
        year: "2003",
        image: "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Peter Jackson (dir.), Elijah Wood, Viggo Mortensen",
        imDbRating: "8.9",
        imDbRatingCount: "1783871"
      },
      {
        id: "tt0110912",
        rank: "8",
        title: "Pulp Fiction",
        fullTitle: "Pulp Fiction (1994)",
        year: "1994",
        image: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Quentin Tarantino (dir.), John Travolta, Uma Thurman",
        imDbRating: "8.9",
        imDbRatingCount: "1990948"
      },
      {
        id: "tt0120737",
        rank: "9",
        title: "The Lord of the Rings: The Fellowship of the Ring",
        fullTitle: "The Lord of the Rings: The Fellowship of the Ring (2001)",
        year: "2001",
        image: "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Peter Jackson (dir.), Elijah Wood, Ian McKellen",
        imDbRating: "8.8",
        imDbRatingCount: "1804981"
      },
      {
        id: "tt0060196",
        rank: "10",
        title: "The Good, the Bad and the Ugly",
        fullTitle: "The Good, the Bad and the Ugly (1966)",
        year: "1966",
        image: "https://m.media-amazon.com/images/M/MV5BNjJlYmNkZGItM2NhYy00MjlmLTk5NmQtNjg1NmM2ODU4OTMwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Sergio Leone (dir.), Clint Eastwood, Eli Wallach",
        imDbRating: "8.8",
        imDbRatingCount: "745015"
      },
      {
        id: "tt0109830",
        rank: "11",
        title: "Forrest Gump",
        fullTitle: "Forrest Gump (1994)",
        year: "1994",
        image: "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Robert Zemeckis (dir.), Tom Hanks, Robin Wright",
        imDbRating: "8.8",
        imDbRatingCount: "2005580"
      },
      {
        id: "tt0137523",
        rank: "12",
        title: "Fight Club",
        fullTitle: "Fight Club (1999)",
        year: "1999",
        image: "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "David Fincher (dir.), Brad Pitt, Edward Norton",
        imDbRating: "8.8",
        imDbRatingCount: "2044949"
      },
      {
        id: "tt1375666",
        rank: "13",
        title: "Inception",
        fullTitle: "Inception (2010)",
        year: "2010",
        image: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Christopher Nolan (dir.), Leonardo DiCaprio, Joseph Gordon-Levitt",
        imDbRating: "8.7",
        imDbRatingCount: "2278668"
      },
      {
        id: "tt0167261",
        rank: "14",
        title: "The Lord of the Rings: The Two Towers",
        fullTitle: "The Lord of the Rings: The Two Towers (2002)",
        year: "2002",
        image: "https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Peter Jackson (dir.), Elijah Wood, Ian McKellen",
        imDbRating: "8.7",
        imDbRatingCount: "1611102"
      },
      {
        id: "tt0080684",
        rank: "15",
        title: "Star Wars: Episode V - The Empire Strikes Back",
        fullTitle: "Star Wars: Episode V - The Empire Strikes Back (1980)",
        year: "1980",
        image: "https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Irvin Kershner (dir.), Mark Hamill, Harrison Ford",
        imDbRating: "8.7",
        imDbRatingCount: "1256297"
      },
      {
        id: "tt0133093",
        rank: "16",
        title: "The Matrix",
        fullTitle: "The Matrix (1999)",
        year: "1999",
        image: "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Lana Wachowski (dir.), Keanu Reeves, Laurence Fishburne",
        imDbRating: "8.7",
        imDbRatingCount: "1864973"
      },
      {
        id: "tt0099685",
        rank: "17",
        title: "Goodfellas",
        fullTitle: "Goodfellas (1990)",
        year: "1990",
        image: "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Martin Scorsese (dir.), Robert De Niro, Ray Liotta",
        imDbRating: "8.7",
        imDbRatingCount: "1122586"
      },
      {
        id: "tt0073486",
        rank: "18",
        title: "One Flew Over the Cuckoo's Nest",
        fullTitle: "One Flew Over the Cuckoo's Nest (1975)",
        year: "1975",
        image: "https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Milos Forman (dir.), Jack Nicholson, Louise Fletcher",
        imDbRating: "8.6",
        imDbRatingCount: "986356"
      },
      {
        id: "tt0114369",
        rank: "19",
        title: "Se7en",
        fullTitle: "Se7en (1995)",
        year: "1995",
        image: "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "David Fincher (dir.), Morgan Freeman, Brad Pitt",
        imDbRating: "8.6",
        imDbRatingCount: "1593970"
      },
      {
        id: "tt0047478",
        rank: "20",
        title: "Seven Samurai",
        fullTitle: "Seven Samurai (1954)",
        year: "1954",
        image: "https://m.media-amazon.com/images/M/MV5BNWQ3OTM4ZGItMWEwZi00MjI5LWI3YzgtNTYwNWRkNmIzMGI5XkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_UX128_CR0,1,128,176_AL_.jpg",
        crew: "Akira Kurosawa (dir.), Toshirô Mifune, Takashi Shimura",
        imDbRating: "8.6",
        imDbRatingCount: "340115"
      },
      {
        id: "tt0038650",
        rank: "21",
        title: "It's a Wonderful Life",
        fullTitle: "It's a Wonderful Life (1946)",
        year: "1946",
        image: "https://m.media-amazon.com/images/M/MV5BZjc4NDZhZWMtNGEzYS00ZWU2LThlM2ItNTA0YzQ0OTExMTE2XkEyXkFqcGdeQXVyNjUwMzI2NzU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Frank Capra (dir.), James Stewart, Donna Reed",
        imDbRating: "8.6",
        imDbRatingCount: "446320"
      },
      {
        id: "tt0102926",
        rank: "22",
        title: "The Silence of the Lambs",
        fullTitle: "The Silence of the Lambs (1991)",
        year: "1991",
        image: "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Jonathan Demme (dir.), Jodie Foster, Anthony Hopkins",
        imDbRating: "8.6",
        imDbRatingCount: "1390365"
      },
      {
        id: "tt0317248",
        rank: "23",
        title: "City of God",
        fullTitle: "City of God (2002)",
        year: "2002",
        image: "https://m.media-amazon.com/images/M/MV5BOTMwYjc5ZmItYTFjZC00ZGQ3LTlkNTMtMjZiNTZlMWQzNzI5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Fernando Meirelles (dir.), Alexandre Rodrigues, Leandro Firmino",
        imDbRating: "8.6",
        imDbRatingCount: "743133"
      },
      {
        id: "tt0120815",
        rank: "24",
        title: "Saving Private Ryan",
        fullTitle: "Saving Private Ryan (1998)",
        year: "1998",
        image: "https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Steven Spielberg (dir.), Tom Hanks, Matt Damon",
        imDbRating: "8.6",
        imDbRatingCount: "1352004"
      },
      {
        id: "tt0118799",
        rank: "25",
        title: "Life Is Beautiful",
        fullTitle: "Life Is Beautiful (1997)",
        year: "1997",
        image: "https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Roberto Benigni (dir.), Roberto Benigni, Nicoletta Braschi",
        imDbRating: "8.6",
        imDbRatingCount: "678692"
      },
      {
        id: "tt0120689",
        rank: "26",
        title: "The Green Mile",
        fullTitle: "The Green Mile (1999)",
        year: "1999",
        image: "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Frank Darabont (dir.), Tom Hanks, Michael Clarke Duncan",
        imDbRating: "8.6",
        imDbRatingCount: "1262414"
      },
      {
        id: "tt0816692",
        rank: "27",
        title: "Interstellar",
        fullTitle: "Interstellar (2014)",
        year: "2014",
        image: "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway",
        imDbRating: "8.6",
        imDbRatingCount: "1739392"
      },
      {
        id: "tt0076759",
        rank: "28",
        title: "Star Wars",
        fullTitle: "Star Wars (1977)",
        year: "1977",
        image: "https://m.media-amazon.com/images/M/MV5BNzg4MjQxNTQtZmI5My00YjMwLWJlMjUtMmJlY2U2ZWFlNzY1XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "George Lucas (dir.), Mark Hamill, Harrison Ford",
        imDbRating: "8.6",
        imDbRatingCount: "1328185"
      },
      {
        id: "tt0103064",
        rank: "29",
        title: "Terminator 2: Judgment Day",
        fullTitle: "Terminator 2: Judgment Day (1991)",
        year: "1991",
        image: "https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "James Cameron (dir.), Arnold Schwarzenegger, Linda Hamilton",
        imDbRating: "8.5",
        imDbRatingCount: "1071724"
      },
      {
        id: "tt0088763",
        rank: "30",
        title: "Back to the Future",
        fullTitle: "Back to the Future (1985)",
        year: "1985",
        image: "https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Robert Zemeckis (dir.), Michael J. Fox, Christopher Lloyd",
        imDbRating: "8.5",
        imDbRatingCount: "1165541"
      },
      {
        id: "tt0245429",
        rank: "31",
        title: "Spirited Away",
        fullTitle: "Spirited Away (2001)",
        year: "2001",
        image: "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Hayao Miyazaki (dir.), Daveigh Chase, Suzanne Pleshette",
        imDbRating: "8.5",
        imDbRatingCount: "735865"
      },
      {
        id: "tt0054215",
        rank: "32",
        title: "Psycho",
        fullTitle: "Psycho (1960)",
        year: "1960",
        image: "https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Alfred Hitchcock (dir.), Anthony Perkins, Janet Leigh",
        imDbRating: "8.5",
        imDbRatingCount: "655504"
      },
      {
        id: "tt0253474",
        rank: "33",
        title: "The Pianist",
        fullTitle: "The Pianist (2002)",
        year: "2002",
        image: "https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY176_CR0,0,128,176_AL_.jpg",
        crew: "Roman Polanski (dir.), Adrien Brody, Thomas Kretschmann",
        imDbRating: "8.5",
        imDbRatingCount: "808182"
      },
      {
        id: "tt0110413",
        rank: "34",
        title: "Léon: The Professional",
        fullTitle: "Léon: The Professional (1994)",
        year: "1994",
        image: "https://m.media-amazon.com/images/M/MV5BODllNWE0MmEtYjUwZi00ZjY3LThmNmQtZjZlMjI2YTZjYmQ0XkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Luc Besson (dir.), Jean Reno, Gary Oldman",
        imDbRating: "8.5",
        imDbRatingCount: "1130480"
      },
      {
        id: "tt6751668",
        rank: "35",
        title: "Parasite",
        fullTitle: "Parasite (2019)",
        year: "2019",
        image: "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Bong Joon Ho (dir.), Song Kang-ho, Sun-kyun Lee",
        imDbRating: "8.5",
        imDbRatingCount: "749741"
      },
      {
        id: "tt0110357",
        rank: "36",
        title: "The Lion King",
        fullTitle: "The Lion King (1994)",
        year: "1994",
        image: "https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Roger Allers (dir.), Matthew Broderick, Jeremy Irons",
        imDbRating: "8.5",
        imDbRatingCount: "1028516"
      },
      {
        id: "tt0172495",
        rank: "37",
        title: "Gladiator",
        fullTitle: "Gladiator (2000)",
        year: "2000",
        image: "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Ridley Scott (dir.), Russell Crowe, Joaquin Phoenix",
        imDbRating: "8.5",
        imDbRatingCount: "1459288"
      },
      {
        id: "tt0120586",
        rank: "38",
        title: "American History X",
        fullTitle: "American History X (1998)",
        year: "1998",
        image: "https://m.media-amazon.com/images/M/MV5BZTJhN2FkYWEtMGI0My00YWM4LWI2MjAtM2UwNjY4MTI2ZTQyXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Tony Kaye (dir.), Edward Norton, Edward Furlong",
        imDbRating: "8.5",
        imDbRatingCount: "1099391"
      },
      {
        id: "tt0114814",
        rank: "39",
        title: "The Usual Suspects",
        fullTitle: "The Usual Suspects (1995)",
        year: "1995",
        image: "https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Bryan Singer (dir.), Kevin Spacey, Gabriel Byrne",
        imDbRating: "8.5",
        imDbRatingCount: "1063681"
      },
      {
        id: "tt0407887",
        rank: "40",
        title: "The Departed",
        fullTitle: "The Departed (2006)",
        year: "2006",
        image: "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Martin Scorsese (dir.), Leonardo DiCaprio, Matt Damon",
        imDbRating: "8.5",
        imDbRatingCount: "1290823"
      },
      {
        id: "tt0482571",
        rank: "41",
        title: "The Prestige",
        fullTitle: "The Prestige (2006)",
        year: "2006",
        image: "https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Christopher Nolan (dir.), Christian Bale, Hugh Jackman",
        imDbRating: "8.5",
        imDbRatingCount: "1298052"
      },
      {
        id: "tt1745960",
        rank: "42",
        title: "Top Gun: Maverick",
        fullTitle: "Top Gun: Maverick (2022)",
        year: "2022",
        image: "https://m.media-amazon.com/images/M/MV5BMmIwZDMyYWUtNTU0ZS00ODJhLTg2ZmEtMTk5ZmYzODcxODYxXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Joseph Kosinski (dir.), Tom Cruise, Jennifer Connelly",
        imDbRating: "8.5",
        imDbRatingCount: "141095"
      },
      {
        id: "tt0034583",
        rank: "43",
        title: "Casablanca",
        fullTitle: "Casablanca (1942)",
        year: "1942",
        image: "https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Michael Curtiz (dir.), Humphrey Bogart, Ingrid Bergman",
        imDbRating: "8.5",
        imDbRatingCount: "561063"
      },
      {
        id: "tt2582802",
        rank: "44",
        title: "Whiplash",
        fullTitle: "Whiplash (2014)",
        year: "2014",
        image: "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Damien Chazelle (dir.), Miles Teller, J.K. Simmons",
        imDbRating: "8.5",
        imDbRatingCount: "813787"
      },
      {
        id: "tt1675434",
        rank: "45",
        title: "The Intouchables",
        fullTitle: "The Intouchables (2011)",
        year: "2011",
        image: "https://m.media-amazon.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Olivier Nakache (dir.), François Cluzet, Omar Sy",
        imDbRating: "8.5",
        imDbRatingCount: "834758"
      },
      {
        id: "tt0027977",
        rank: "46",
        title: "Modern Times",
        fullTitle: "Modern Times (1936)",
        year: "1936",
        image: "https://m.media-amazon.com/images/M/MV5BYjJiZjMzYzktNjU0NS00OTkxLWEwYzItYzdhYWJjN2QzMTRlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard",
        imDbRating: "8.4",
        imDbRatingCount: "238095"
      },
      {
        id: "tt0056058",
        rank: "47",
        title: "Hara-Kiri",
        fullTitle: "Hara-Kiri (1962)",
        year: "1962",
        image: "https://m.media-amazon.com/images/M/MV5BYjBmYTQ1NjItZWU5MS00YjI0LTg2OTYtYmFkN2JkMmNiNWVkXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_UY176_CR0,0,128,176_AL_.jpg",
        crew: "Masaki Kobayashi (dir.), Tatsuya Nakadai, Akira Ishihama",
        imDbRating: "8.4",
        imDbRatingCount: "54379"
      },
      {
        id: "tt0064116",
        rank: "48",
        title: "Once Upon a Time in the West",
        fullTitle: "Once Upon a Time in the West (1968)",
        year: "1968",
        image: "https://m.media-amazon.com/images/M/MV5BODQ3NDExOGYtMzI3Mi00NWRlLTkwNjAtNjc4MDgzZGJiZTA1XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Sergio Leone (dir.), Henry Fonda, Charles Bronson",
        imDbRating: "8.4",
        imDbRatingCount: "324134"
      },
      {
        id: "tt0095327",
        rank: "49",
        title: "Grave of the Fireflies",
        fullTitle: "Grave of the Fireflies (1988)",
        year: "1988",
        image: "https://m.media-amazon.com/images/M/MV5BZmY2NjUzNDQtNTgxNC00M2Q4LTljOWQtMjNjNDBjNWUxNmJlXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Isao Takahata (dir.), Tsutomu Tatsumi, Ayano Shiraishi",
        imDbRating: "8.4",
        imDbRatingCount: "268191"
      },
      {
        id: "tt0047396",
        rank: "50",
        title: "Rear Window",
        fullTitle: "Rear Window (1954)",
        year: "1954",
        image: "https://m.media-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Alfred Hitchcock (dir.), James Stewart, Grace Kelly",
        imDbRating: "8.4",
        imDbRatingCount: "481974"
      },
      {
        id: "tt0078748",
        rank: "51",
        title: "Alien",
        fullTitle: "Alien (1979)",
        year: "1979",
        image: "https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NGE5LWEyYmMtOGQ1ZGZjNmRkYjFhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Ridley Scott (dir.), Sigourney Weaver, Tom Skerritt",
        imDbRating: "8.4",
        imDbRatingCount: "856952"
      },
      {
        id: "tt0021749",
        rank: "52",
        title: "City Lights",
        fullTitle: "City Lights (1931)",
        year: "1931",
        image: "https://m.media-amazon.com/images/M/MV5BY2I4MmM1N2EtM2YzOS00OWUzLTkzYzctNDc5NDg2N2IyODJmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Charles Chaplin (dir.), Charles Chaplin, Virginia Cherrill",
        imDbRating: "8.4",
        imDbRatingCount: "182109"
      },
      {
        id: "tt0095765",
        rank: "53",
        title: "Cinema Paradiso",
        fullTitle: "Cinema Paradiso (1988)",
        year: "1988",
        image: "https://m.media-amazon.com/images/M/MV5BM2FhYjEyYmYtMDI1Yy00YTdlLWI2NWQtYmEzNzAxOGY1NjY2XkEyXkFqcGdeQXVyNTA3NTIyNDg@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Giuseppe Tornatore (dir.), Philippe Noiret, Enzo Cannavale",
        imDbRating: "8.4",
        imDbRatingCount: "255527"
      },
      {
        id: "tt0209144",
        rank: "54",
        title: "Memento",
        fullTitle: "Memento (2000)",
        year: "2000",
        image: "https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Christopher Nolan (dir.), Guy Pearce, Carrie-Anne Moss",
        imDbRating: "8.4",
        imDbRatingCount: "1210542"
      },
      {
        id: "tt0078788",
        rank: "55",
        title: "Apocalypse Now",
        fullTitle: "Apocalypse Now (1979)",
        year: "1979",
        image: "https://m.media-amazon.com/images/M/MV5BMDdhODg0MjYtYzBiOS00ZmI5LWEwZGYtZDEyNDU4MmQyNzFkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Francis Ford Coppola (dir.), Martin Sheen, Marlon Brando",
        imDbRating: "8.4",
        imDbRatingCount: "653188"
      },
      {
        id: "tt0082971",
        rank: "56",
        title: "Indiana Jones and the Raiders of the Lost Ark",
        fullTitle: "Indiana Jones and the Raiders of the Lost Ark (1981)",
        year: "1981",
        image: "https://m.media-amazon.com/images/M/MV5BNTU2ODkyY2MtMjU1NC00NjE1LWEzYjgtMWQ3MzRhMTE0NDc0XkEyXkFqcGdeQXVyMjM4MzQ4OTQ@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Steven Spielberg (dir.), Harrison Ford, Karen Allen",
        imDbRating: "8.4",
        imDbRatingCount: "946201"
      },
      {
        id: "tt1853728",
        rank: "57",
        title: "Django Unchained",
        fullTitle: "Django Unchained (2012)",
        year: "2012",
        image: "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Quentin Tarantino (dir.), Jamie Foxx, Christoph Waltz",
        imDbRating: "8.4",
        imDbRatingCount: "1501331"
      },
      {
        id: "tt0910970",
        rank: "58",
        title: "WALL·E",
        fullTitle: "WALL·E (2008)",
        year: "2008",
        image: "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Andrew Stanton (dir.), Ben Burtt, Elissa Knight",
        imDbRating: "8.4",
        imDbRatingCount: "1087710"
      },
      {
        id: "tt0405094",
        rank: "59",
        title: "The Lives of Others",
        fullTitle: "The Lives of Others (2006)",
        year: "2006",
        image: "https://m.media-amazon.com/images/M/MV5BNmQyNmJjM2ItNTQzYi00ZjMxLWFjMDYtZjUyN2YwZDk5YWQ2XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Florian Henckel von Donnersmarck (dir.), Ulrich Mühe, Martina Gedeck",
        imDbRating: "8.4",
        imDbRatingCount: "384192"
      },
      {
        id: "tt0043014",
        rank: "60",
        title: "Sunset Blvd.",
        fullTitle: "Sunset Blvd. (1950)",
        year: "1950",
        image: "https://m.media-amazon.com/images/M/MV5BMTU0NTkyNzYwMF5BMl5BanBnXkFtZTgwMDU0NDk5MTI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Billy Wilder (dir.), William Holden, Gloria Swanson",
        imDbRating: "8.4",
        imDbRatingCount: "218261"
      },
      {
        id: "tt0050825",
        rank: "61",
        title: "Paths of Glory",
        fullTitle: "Paths of Glory (1957)",
        year: "1957",
        image: "https://m.media-amazon.com/images/M/MV5BOTI5Nzc0OTMtYzBkMS00NjkxLThmM2UtNjM2ODgxN2M5NjNkXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Stanley Kubrick (dir.), Kirk Douglas, Ralph Meeker",
        imDbRating: "8.4",
        imDbRatingCount: "194003"
      },
      {
        id: "tt0081505",
        rank: "62",
        title: "The Shining",
        fullTitle: "The Shining (1980)",
        year: "1980",
        image: "https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Stanley Kubrick (dir.), Jack Nicholson, Shelley Duvall",
        imDbRating: "8.4",
        imDbRatingCount: "989175"
      },
      {
        id: "tt0032553",
        rank: "63",
        title: "The Great Dictator",
        fullTitle: "The Great Dictator (1940)",
        year: "1940",
        image: "https://m.media-amazon.com/images/M/MV5BMmExYWJjNTktNGUyZS00ODhmLTkxYzAtNWIzOGEyMGNiMmUwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard",
        imDbRating: "8.4",
        imDbRatingCount: "220758"
      },
      {
        id: "tt0051201",
        rank: "64",
        title: "Witness for the Prosecution",
        fullTitle: "Witness for the Prosecution (1957)",
        year: "1957",
        image: "https://m.media-amazon.com/images/M/MV5BNDQwODU5OWYtNDcyNi00MDQ1LThiOGMtZDkwNWJiM2Y3MDg0XkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Billy Wilder (dir.), Tyrone Power, Marlene Dietrich",
        imDbRating: "8.4",
        imDbRatingCount: "122605"
      },
      {
        id: "tt4154756",
        rank: "65",
        title: "Avengers: Infinity War",
        fullTitle: "Avengers: Infinity War (2018)",
        year: "2018",
        image: "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Anthony Russo (dir.), Robert Downey Jr., Chris Hemsworth",
        imDbRating: "8.4",
        imDbRatingCount: "1022201"
      },
      {
        id: "tt0090605",
        rank: "66",
        title: "Aliens",
        fullTitle: "Aliens (1986)",
        year: "1986",
        image: "https://m.media-amazon.com/images/M/MV5BZGU2OGY5ZTYtMWNhYy00NjZiLWI0NjUtZmNhY2JhNDRmODU3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "James Cameron (dir.), Sigourney Weaver, Michael Biehn",
        imDbRating: "8.3",
        imDbRatingCount: "701685"
      }
    ]